ADX-877 PDF preview issue
fjelltopp/adx_develop pull request #126
Opened 2022-12-19 12:29 UTC by kforenc

2022-12-19 12:31 UTC, tomeksabala requested changes
What happens with content-disposition and content-type when giftless serves non pdf files?
We need to preserve the headers values for those cases.

2022-12-19 13:46 UTC, kforenc commented
IMO they get dropped - I couldn't test 100% since I don't know what other types are stored in giftless, that browser can understand. We can't preserve them, at least I can't. Nginx prevents hiding of headers when used in 'if' of server clause. But maybe using a custom module could help - i.e. lua-nginx-module?

2022-12-19 13:55 UTC, kforenc commented
Another option would be to understand why giftless doesn't get information to show inline - to check it I need to debug with S3 as backend. IMO this is a much cleaner solution, which ofc could end up with modification of blob-storage, giftless or both (but it's less probable).

2023-01-03 10:57 UTC, tomeksabala approved these changes

2023-01-03 12:07 UTC, merged