ADX-619 Add local fake SMTP server, add missing ERROR EMAIL variables
fjelltopp/adx_develop pull request #52
Opened 2021-03-08 09:30 UTC by fulior

https://github.com/rnwood/smtp4dev
Adds a local web console that allows to review received emails.

2021-03-08 09:40 UTC, tomeksabala approved these changes

2021-03-08 09:41 UTC, tomeksabala requested changes
nginx container got commited into this by mistake?

2021-03-08 09:46 UTC, fulior commented
> nginx container got commited into this by mistake?
Right, fixed :)

2021-03-09 08:24 UTC, tomeksabala approved these changes
Looks good to me! :)

2021-03-09 08:51 UTC, merged