ADX-747 improve test command.
fjelltopp/adx_develop pull request #74
Opened 2021-09-28 14:58 UTC by jonathansberry

Improving the utility test command to make it work with pdb,  allow you to gracefully stop pytest mid-testing and specify that specific tests that you want to run.

2021-09-29 07:18 UTC, jonathansberry commented
The build is failing because The input `device is not tty`.  I have changed `adx test` command to run `docker exec` in interactive mode which seems to be causing the problem.  I'm keen to keep the exec command in interactive mode by default, as it greatly improves the way you use the command locally.  I would love to hear from @Michał Ful (when he is next working) what he thinks the best solution is.  One option is to add a command option that runs the `adx test` command in non-interactive mode, then update the `ci_test.sh` script to use this option.  But maybe there is a better way?

2021-09-29 07:23 UTC, tomeksabala requested changes

2021-09-29 07:23 UTC, tomeksabala commented on adx
> +)
That's redundant as you can already pass pytest `-k` args specifying keywords to filter out test cases:
https://docs.pytest.org/en/6.2.x/usage.html#specifying-tests-selecting-tests
e.g.
```
# all test from a module
adx test validation -k test_custom_checks
# complex matching, double quotes needed so " are passed to docker-compose command
adx test validation -k '"test_custom_checks and test_check_custom_constraint_for_missing_data"'
```

2021-09-29 07:23 UTC, tomeksabala commented on util/__init__.py
> +        f'ckan /usr/local/bin/ckan-pytest -s --disable-warnings '
it's better to use full args so it's clear what's configured. What does `-s` do? Can you replace it with `--full-argument`?

2021-09-30 06:36 UTC, tomeksabala approved these changes

2021-09-30 10:53 UTC, merged