ADX-789 Translation script
fjelltopp/adx_develop pull request #83
Opened 2022-01-31 14:34 UTC by jonathansberry

This is optional.  It's a little script I built to update and prepare all catalogs for sending to Ian for translation. It runs all the necessary commands and copies all the po files into one folder structure so they can be really easily zipped and sent to Ian. 

There's the second task of then copying the translated catalogs received from Ian into the right place and committing them to github. I havn't addressed this task in this PR. 

If you think it is worth committing, I should first update the readme prior to merging this PR.

2022-01-31 17:56 UTC, tomeksabala requested changes
This looks very useful. I think it must be integrated with `adx` client and documented in the README.md so everyone in the team could use it easily in the future.
There are a few limitations that I see, but they might be not worth the additional effort. What do you think?:
1. script has fixed file paths which makes it only runnable from within running adr container and less easy to keep up to date if we modify dir structure. This could be fixed by reading the absolute path of the script and then using relative paths for extension dirs, etc.
2. The script would integrate better with adx_develop if it was in python

2022-01-31 17:56 UTC, tomeksabala commented on translations/translate.bash
> +# To use this script: `adx bash ckan` followed by `bash /usr/lib/adx/adx_develop/translations/translate.bash`
Can you rename the script to `translate.sh` so it's consistent with other scripts in the repo?

2022-01-31 17:56 UTC, tomeksabala commented on .gitignore
> +translations/**/
maybe make it a subdirectory like `build` to indicate those are artefacts outputs safe to remove.
e.g.
```
build/translations/*
```

2022-02-02 17:56 UTC, jonathansberry commented
Right I think I've addressed the two comments, and I think we should call it at that.  I know it isn't part of the adx script yet, but I don't want to give the impression it is a robust well tested piece of code that people should expect any sort of UX from. It needs to be used again, and probably by someone else  before we can consider that I think. We've taken a good step forwards this time round.   If we find ourselves having to do another update of translations in the future we can take another step forwards then.

2022-02-03 08:07 UTC, tomeksabala approved these changes

2022-02-03 08:21 UTC, merged